#!/bin/sh

down() {
brightnessctl s +5%
brightness=$(brightnessctl g)
max_brightness=$(brightnessctl m)
brightness_percentage=$((brightness * 100 / max_brightness))

dunstify -a "BRIGHTNESS" "Decreasing to $brightness_percentage%" -h int:value:"$brightness_percentage" -i ~/.config/dunst/assets/ui/brightness-down.png -r 2593 -u normal
}

up() {
brightnessctl s 5%-
brightness=$(brightnessctl g)
max_brightness=$(brightnessctl m)
brightness_percentage=$((brightness * 100 / max_brightness))

dunstify -a "BRIGHTNESS" "Increasing to $brightness_percentage%" -h int:value:"$brightness_percentage" -i ~/.config/dunst/assets/ui/brightness-up.png -r 2593 -u normal
}

case "$1" in
  up) up;;
  down) down;;
esac
